### ISSUE TITLE
Error when updating host, who already have macro

### ISSUE THREAD

**Issue by andyzasl** [r0bj/ansible-zabbix-api#5]
TASK: [add-host-to-zabbix | sync host with zabbix] ****************************
failed: [XXX.XXX.XXX.XXX] => {"failed": true, "parsed": false}
BECOME-SUCCESS-gwzstkkqbghamsvvynimornizrtlmckp
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1434540025.65-71459539167281/zabbix-api", line 2217, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1434540025.65-71459539167281/zabbix-api", line 581, in main
    templates,
  File "/home/user/.ansible/tmp/ansible-tmp-1434540025.65-71459539167281/zabbix-api", line 392, in sync_host
    self.__compare_macros(hostdump, macros_list)
  File "/home/user/.ansible/tmp/ansible-tmp-1434540025.65-71459539167281/zabbix-api", line 365, in __compare_macros
    if dump_macro['macro'] + dump_macro['value'] not in keyvalues:

**Comment by r0bj** [comment]
Thanks @andyzasl 
It seems that there is missing last part of stack trace, could you please provide full version of error message generated?

**Comment by andyzasl** [comment]
No, this was all trace i've seen :(
